# Generated by Django 5.2.17 on 2026-10-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
